jenkins2-primary:
  image: "yunlzheng/rancher-jenkins2"
  labels:
    io.rancher.sidekicks: jenkins2-plugins,jenkins2-datavolume
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - jenkins2-plugins
    - jenkins2-datavolume
jenkins2-plugins:
  image: "yunlzheng/rancher-jenkins2:plugins2"
  labels:
    io.rancher.container.start_once: true
jenkins2-datavolume:
  image: "yunlzheng/rancher-jenkins2:data"
  volumes:
    - /var/jenkins_home
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
